version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    env_file:
      - ./frontend/.env.prod
    networks:
      - app-network

  backend-1a:
    build: ./backend-1
    container_name: backend-1a
    env_file:
      - ./backend-1/.env
    environment:
      - PORT=3010
    networks:
      - app-network

  backend-1b:
    build: ./backend-1
    container_name: backend-1b
    env_file:
      - ./backend-1/.env
    environment:
      - PORT=3010
    networks:
      - app-network

  backend-1c:
    build: ./backend-1
    container_name: backend-1c
    env_file:
      - ./backend-1/.env
    environment:
      - PORT=3010
    networks:
      - app-network

  backend-2a:
    build: ./backend-2
    container_name: backend-2a
    env_file:
      - ./backend-2/.env
    environment:
      - PORT=3020
    networks:
      - app-network

  backend-2b:
    build: ./backend-2
    container_name: backend-2b
    env_file:
      - ./backend-2/.env
    environment:
      - PORT=3020
    networks:
      - app-network

  backend-2c:
    build: ./backend-2
    container_name: backend-2c
    env_file:
      - ./backend-2/.env
    environment:
      - PORT=3020
    networks:
      - app-network

  consumer:
    build: ./consumer
    container_name: consumer
    env_file:
      - ./consumer/.env
    environment:
      - PORT=3030
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend-1a
      - backend-1b
      - backend-1c
      - backend-2a
      - backend-2b
      - backend-2c
      - consumer
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
